In [1]:
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
team= "Torino"
opp= "Milan"

In [3]:
df_team= pd.read_csv(f"../Data/{team}.csv")
df_team

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Torino,Milan,2024-08-17,D,A,2,2,0,1,0,...,1.0,0.8,0.0,0.0,0.0,0.14,0,0.8,0.17,-1.2
1,Torino,Atalanta,2024-08-25,W,H,2,1,1,2,0,...,1.6,0.8,-0.4,-0.4,-0.6,0.20,1,4.2,0.42,3.2
2,Torino,Venezia,2024-08-30,W,A,1,0,1,1,0,...,0.5,1.2,0.0,0.0,0.5,0.09,0,0.8,0.21,0.8
3,Torino,Lecce,2024-09-15,D,H,0,0,0,0,0,...,0.4,0.6,-0.4,-0.4,-0.4,0.09,1,1.6,0.27,1.6
4,Torino,Hellas Verona,2024-09-20,W,A,3,2,1,3,0,...,0.5,1.0,0.8,1.5,0.5,0.10,1,1.5,0.74,-0.5
5,Torino,Lazio,2024-09-29,L,H,2,3,-1,2,0,...,0.6,0.8,1.3,1.3,1.4,0.06,1,2.2,0.32,-0.8
6,Torino,Inter,2024-10-05,L,A,2,3,-1,1,1,...,0.7,0.3,0.4,0.2,0.3,0.14,0,3.2,0.41,0.2
7,Torino,Cagliari,2024-10-20,L,A,2,3,-1,2,0,...,1.0,1.2,0.6,0.6,1.0,0.08,1,1.3,0.31,-0.7
8,Torino,Como,2024-10-25,W,H,1,0,1,1,0,...,0.4,0.3,-0.3,-0.3,-0.4,0.16,0,0.6,0.10,0.6
9,Torino,Roma,2024-10-31,L,A,0,1,-1,0,0,...,0.1,0.5,-0.2,-0.2,-0.1,0.05,0,0.7,0.25,-0.3
10,Torino,Fiorentina,2024-11-03,L,H,0,1,-1,0,0,...,0.5,0.3,-0.6,-0.6,-0.5,0.06,1,0.3,0.10,-0.7
11,Torino,Juventus,2024-11-09,L,A,0,2,-2,0,0,...,0.1,0.3,-0.4,-0.4,-0.1,0.07,0,1.6,0.41,-0.4
12,Torino,Monza,2024-11-24,D,H,1,1,0,1,0,...,0.9,0.9,0.0,0.0,0.1,0.09,0,1.7,0.28,0.7
13,Torino,Napoli,2024-12-01,L,H,0,1,-1,0,0,...,0.2,1.5,-0.3,-0.3,-0.2,0.05,0,1.3,0.21,0.3
14,Torino,Genoa,2024-12-07,D,A,0,0,0,0,0,...,0.4,0.9,-0.6,-0.6,-0.4,0.06,0,0.2,0.19,0.2
15,Torino,Empoli,2024-12-13,W,A,1,0,1,1,0,...,0.7,0.5,0.0,0.0,0.3,0.07,0,0.1,0.04,0.1
16,Torino,Bologna,2024-12-21,L,H,0,2,-2,0,0,...,0.3,0.6,-0.3,-0.3,-0.3,0.04,0,2.3,0.32,0.3
17,Torino,Udinese,2024-12-29,D,A,2,2,0,2,0,...,0.4,0.4,1.4,1.4,0.6,0.05,0,1.8,0.59,-0.2
18,Torino,Parma,2025-01-05,D,H,0,0,0,0,0,...,0.8,0.6,-1.1,-1.1,-0.8,0.09,0,0.1,0.03,0.1
19,Torino,Juventus,2025-01-11,D,H,1,1,0,1,0,...,0.3,0.6,0.4,0.4,0.7,0.05,0,1.0,0.11,0.0
20,Torino,Fiorentina,2025-01-19,D,A,1,1,0,1,0,...,0.1,0.4,0.6,0.6,-0.1,0.07,1,1.2,0.22,0.2
21,Torino,Cagliari,2025-01-24,W,H,2,0,2,2,0,...,1.4,0.8,0.5,0.5,-0.4,0.08,0,0.0,0.03,0.0
22,Torino,Atalanta,2025-02-01,D,A,1,1,0,1,0,...,0.6,0.4,0.4,0.4,0.4,0.13,0,3.0,0.22,2.0
23,Torino,Genoa,2025-02-08,D,H,1,1,0,0,0,...,0.6,0.9,-0.7,-0.7,-0.6,0.07,0,0.4,0.20,-0.6
24,Torino,Bologna,2025-02-14,L,A,2,3,-1,2,0,...,0.7,0.7,1.0,1.0,0.3,0.12,0,1.3,0.06,-0.7

In [4]:
df_opp= pd.read_csv(f"../Data/{opp}.csv")
df_opp

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Milan,Torino,2024-08-17,D,H,2,2,0,2,0,...,1.3,1.3,-0.1,-0.1,-0.3,0.08,0,1.3,0.44,0.3
1,Milan,Parma,2024-08-24,L,A,1,2,-1,1,0,...,1.9,1.4,-0.9,-0.9,-0.9,0.12,0,1.4,0.28,-0.6
2,Milan,Lazio,2024-08-31,D,A,2,2,0,2,0,...,1.2,0.8,0.7,0.7,0.8,0.13,1,1.9,0.47,-0.1
3,Milan,Venezia,2024-09-14,W,H,4,0,4,2,2,...,0.7,0.7,1.8,1.3,1.3,0.07,0,0.0,0.03,0.0
4,Milan,Inter,2024-09-22,W,A,2,1,1,2,0,...,1.2,1.1,0.3,0.3,-0.2,0.11,0,1.0,0.26,0.0
5,Milan,Lecce,2024-09-27,W,H,3,0,3,3,0,...,1.1,0.8,1.4,1.4,0.9,0.11,0,0.5,0.07,0.5
6,Milan,Fiorentina,2024-10-06,L,A,1,2,-1,1,0,...,1.1,1.1,-1.6,0.0,-0.1,0.07,0,1.4,0.21,-0.6
7,Milan,Udinese,2024-10-19,W,H,1,0,1,1,0,...,0.8,0.5,-0.2,-0.2,0.2,0.12,0,0.1,0.11,0.1
8,Milan,Napoli,2024-10-29,L,H,0,2,-2,0,0,...,0.6,1.2,-0.7,-0.7,-0.6,0.05,0,1.4,0.35,-0.6
9,Milan,Monza,2024-11-02,W,A,1,0,1,1,0,...,1.8,1.0,-1.5,-1.5,-1.8,0.14,0,0.2,0.11,0.2
10,Milan,Cagliari,2024-11-09,D,A,3,3,0,3,0,...,2.4,1.4,-0.3,-0.3,-0.4,0.26,0,1.5,0.24,-1.5
11,Milan,Juventus,2024-11-23,D,H,0,0,0,0,0,...,0.2,0.4,-0.3,-0.3,-0.2,0.05,1,0.1,0.05,0.1
12,Milan,Empoli,2024-11-30,W,H,3,0,3,3,0,...,1.7,1.4,0.7,0.7,0.3,0.11,0,0.0,NaN,0.0
13,Milan,Atalanta,2024-12-06,L,A,1,2,-1,1,0,...,0.7,0.8,0.3,0.3,0.3,0.12,0,2.0,0.25,0.0
14,Milan,Genoa,2024-12-15,D,H,0,0,0,0,0,...,1.0,1.3,-1.1,-1.1,-1.0,0.05,0,0.0,NaN,0.0
15,Milan,Hellas Verona,2024-12-20,W,A,1,0,1,1,0,...,0.6,0.7,0.2,0.2,0.4,0.06,0,0.4,0.18,0.4
16,Milan,Roma,2024-12-29,D,H,1,1,0,1,0,...,1.6,1.3,-0.9,-0.9,-0.6,0.09,0,1.0,0.19,0.0
17,Milan,Cagliari,2025-01-11,D,H,1,1,0,1,0,...,1.7,0.9,-1.7,-1.7,-1.7,0.12,0,0.4,0.18,-0.6
18,Milan,Como,2025-01-14,W,A,2,1,1,2,0,...,0.9,0.6,0.7,0.7,0.1,0.11,0,0.5,0.12,-0.5
19,Milan,Juventus,2025-01-18,L,A,0,2,-2,0,0,...,1.0,0.8,-0.9,-0.9,-1.0,0.07,0,0.8,0.13,-1.2
20,Milan,Parma,2025-01-26,W,H,3,2,1,2,1,...,1.2,0.8,0.8,0.5,0.8,0.12,1,1.9,0.43,-0.1
21,Milan,Inter,2025-02-02,D,H,1,1,0,1,0,...,0.3,0.4,0.4,0.4,-0.3,0.06,0,1.6,0.28,0.6
22,Milan,Empoli,2025-02-08,W,A,2,0,2,2,0,...,1.1,0.6,0.7,0.7,0.9,0.08,1,0.0,NaN,0.0
23,Milan,Hellas Verona,2025-02-15,W,H,1,0,1,1,0,...,1.8,1.9,-1.1,-1.1,-0.8,0.12,0,0.7,0.34,0.7